# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile uses configuration v2
Vagrant.configure(2) do |config|
  # This Vagrantfile uses an ubuntu lucid 64 box as the base
  config.vm.box = "f500/ubuntu-lucid64"

  # forward request to my host machine's port 8080
  # to the port 8080 in the vm
  config.vm.network :forwarded_port, host: 8000, guest: 8080

  # Prevent updates that havne't been requested manually
  config.vm.box_check_update = false
  
  # fine tune virtual box resources for the vm
  config.vm.provider "virtualbox" do |vb|
    # Share only 2GB of memory with the vm
    vb.memory = "2048"
  end

  # install java
  config.vm.provision :shell, 
  inline: 'wget --no-check-certificate https://github.com/aglover/ubuntu-equip/raw/master/equip_java7_64.sh && bash equip_java7_64.sh'

  #install gcc
  config.vm.provision :shell,
  inline: 'sudo apt-get install gcc-4.1'


  # install VirtualBox

end
